=== swatisss/exercise/xml/dtdbook.dtd
<!ELEMENT product (book+)>
<!ELEMENT book (code,title,name,price,meibo)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (tax-excluded|tax-included)>
<!ELEMENT tax-excluded (#PCDATA)>
<!ELEMENT tax-included (#PCDATA)>
<!ELEMENT meibo (shain+)>
<!ELEMENT shain (mcode,mname,address,salary)>
<!ELEMENT mcode (#PCDATA)>
<!ELEMENT mname (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ENTITY name1 SYSTEM "dtdbook.dtd">
<!ENTITY filename SYSTEM "dtdbook.dtd">

=== swatisss/exercise/xml/book1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE product SYSTEM "dtdbook.dtd">

<product>
	<book>
		<code>001</code>
		<title>Java入門</title>
		<name>&name1;</name>
		<price>
			<tax-excluded>2800</tax-excluded>
		</price>
		<meibo>&filename;</meibo>
	</book>
	<book>
		<code>002</code>
		<title>C言語応用</title>
		<name>&name1;</name>
		<price>
			<tax-included>3500</tax-included>
		</price>
		<meibo>&filename;</meibo>
	</book>
 </product>
